name: service_1
version: '1.0.0'
config-version: 2
profile: default

model-paths: ["models"]
seed-paths: ["seeds"]

seeds:
  service_1:
    +full_refresh: false
    +meta:
      owner: "test"
      criticality: "CORE"

models:
  service_1:
    +materialized: table
    +meta:
      owner: "test"
      criticality: "CORE"
    table_a:
      +tags: ["e2e-schedule"]
    table_b:
      +tags: ["e2e-schedule"]
    table_c:
      +tags: ["e2e-schedule"]
    ftable_a:
      +tags: ["e2e-schedule-failure"]
    ftable_b:
      +tags: ["e2e-schedule-failure"]
    rel_probe:
      +tags: ["rel-probe"]
    rel_probe_up:
      +tags: ["rel-probe"]
    rel_probe_down:
      +tags: ["rel-probe"]
