name: core
version: '1.0.1'
config-version: 2
profile: default

model-paths: ["models"]
seed-paths: ["seeds"]

seeds:
  core:
    +full_refresh: false
    +meta:
      owner: "core"
      criticality: "CORE"

models:
  core:
    +materialized: table
    +meta:
      owner: "core"
      criticality: "CORE"
