name: service_2
version: '1.0.0'
config-version: 2
profile: default

model-paths: ["models"]

models:
  service_2:
    +materialized: table
    +meta:
      owner: "test"
      criticality: "CORE"
    table_g:
      +tags: ["e2e-schedule"]
    table_h:
      +tags: ["e2e-schedule"]
    ftable_d:
      +tags: ["e2e-schedule-failure"]
    ftable_e:
      +tags: ["e2e-schedule-failure"]
    ftable_h:
      +tags: ["e2e-schedule-failure"]
